/**
 * Common constants for all features.
 */
/**
 * The number of columns for XS device.
 */
export const COLUMN_XS: number = 4;
export const TAB_CONTENT_WIDTH: string = '100%';

/**
 * The number of columns for SM device.
 */
export const COLUMN_SM: number = 4;

/**
 * The number of columns for MD device.
 */
export const COLUMN_MD: number = 8;

/**
 * The number of columns for LG device.
 */
export const COLUMN_LG: number = 12;

/**
 * The number of span for XS device.
 */
export const SPAN_XS: number = 4;

/**
 * The number of span for SM device.
 */
export const SPAN_SM: number = 4;

/**
 * The number of span for MD device.
 */
export const SPAN_MD: number = 4;

/**
 * The number of span for LG device.
 */
export const SPAN_LG: number = 4;

/**
 * The number of offset for XS device.
 */
export const OFFSET_XS: number = 0;

/**
 * The number of offset for SM device.
 */
export const OFFSET_SM: number = 0;

/**
 * The number of offset for MD device.
 */
export const OFFSET_MD: number = 2;

/**
 * The number of offset for LG device.
 */
export const OFFSET_LG: number = 4;

/**
 * Font weight of the list.
 */
export const LIST_FONT_WEIGHT: number = 500;

/**
 *Width of the list.
 */
export const LIST_WIDTH: string = '100%';

/**
 * The percentage of width of the list item.
 */
export const LIST_ITEM_WIDTH: string = '100%';

/**
 * The percentage of height of the column.
 */
export const COLUMN_HEIGHT: string = '100%';

/**
 * The name of the bundleName.
 */
export const BUNDLE_NAME: string = 'com.example.myapplication';

/**
 * The name of the abilityName.
 */
export const ABILITY_NAME: string = 'ResponsiveLayoutItemAbility';

/**
 * Initialize device breakpoints.
 */
export const BREAKPOINTS_INITIALIZE_NAME: string = 'md';

/**
 * Localization ability.
 */
export const LOCATION_CAPABILITY: string = 'SystemCapability.Location.Location.Core';

/**
 * Breakpoint name.
 */
export const BREAKPOINT_SYSTEM_NAME: string = 'mainBreakpoint';

/**
 * The percentage of height of column component.
 */
export const SYSTEM_COLUMN_HEIGHT: string = '100%';

/**
 * The percentage of width of column component.
 */
export const SYSTEM_COLUMN_WIDTH: string = '100%';

/**
 * The percentage of width of row component.
 */
export const SYSTEM_ROW_WIDTH: string = '100%';

/**
 * Font weight of text component.
 */
export const TEXT_FONT_WEIGHT: number = 500;

/**
 * The percentage of width of column component.
 */
export const ADAPTIVE_COLUMN_WIDTH: string = '100%';

/**
 * The percentage of height of column component.
 */
export const ADAPTIVE_COLUMN_HEIGHT: string = '100%';

/**
 * The percentage of height of column component.
 */
export const ADAPTIVE_FLEXIBLE_COLUMN_WIDTH: string = '100%';

/**
 * The value of shrink of column component.
 */
export const ADAPTIVE_FLEX_SHRINK: number = 1;


/**
 * Common constants for all features.
 */
/**
 * Breakpoint sm.
 */
export const BREAKPOINTS_SM_NAME: string = 'sm';

/**
 * Breakpoint md.
 */
export const BREAKPOINTS_MD_NAME: string = 'md';

/**
 * Breakpoint lg.
 */
export const BREAKPOINTS_LG_NAME: string = 'lg';

/**
 * Breakpoint xl.
 */
export const BREAKPOINTS_XL_NAME: string = 'xl';

/**
 * The value of tab vertical in sm device.
 */
export const TAB_SM_VERTICAL: boolean = false;

/**
 * The value of tab vertical in md device.
 */
export const TAB_MD_VERTICAL: boolean = false;

/**
 * The value of tab vertical in lg device.
 */
export const TAB_LG_VERTICAL: boolean = true;

/**
 * The value of tab vertical in xl device.
 */
export const TAB_XL_VERTICAL: boolean = true;

/**
 * The percentage of width of tab bar in sm device.
 */
export const TAB_SM_BAR_WIDTH: string = '100%';

/**
 * The percentage of width of tab bar in md device.
 */
export const TAB_MD_BAR_WIDTH: string = '100%';

/**
 * The width of tab bar in lg device.
 */
export const TAB_LG_BAR_WIDTH: string = '96vp';

/**
 * The width of tab bar in xl device.
 */
export const TAB_XL_BAR_WIDTH: string = '96vp';

/**
 * The height of tab bar in sm device.
 */
export const TAB_SM_BAR_HEIGHT: string = '56vp';

/**
 * The height of tab bar in md device.
 */
export const TAB_MD_BAR_HEIGHT: string = '56vp';

/**
 * The percentage of height tab bar in lg device.
 */
export const TAB_LG_BAR_HEIGHT: string = '60%';

/**
 * The percentage of height tab bar in xl device.
 */
export const TAB_XL_BAR_HEIGHT: string = '60%';

/**
 * The percentage of width of tab content.
 */

/**
 * The percentage of height of tab content.
 */
export const TAB_CONTENT_HEIGHT: string = '100%';

/**
 * The percentage of width of flex component.
 */
export const FLEX_TAB_BAR_WIDTH: string = '100%';

/**
 * The percentage of height of flex component.
 */
export const FLEX_TAB_BAR_HEIGHT: string = '100%';

/**
 * The percentage of height in row component.
 */
export const FIRST_TAB_CHOOSE_INDEX: number = 0;

/**
 * The percentage of height in row component.
 */

/**
 * The number of tab component.
 */
export const TAB_SIZE: number = 4;

/**
 * The number of grid item.
 */
export const GRID_SIZE: number = 8;

/**
 * Initialize device breakpoints.
 */

/**
 *  The value of aspect ratio in column component.
 */
export const COLUMN_ASPECT_RATIO: number = 16 / 9;

/**
 * Font weight of text component.
 */
export const COLUMN_TEXT_FONT_WEIGHT: number = 400;

/**
 *  The percentage of width of row component.
 */
export const ROW_WIDTH: string = '100%';

/**
 * The value of  attribute of columnsTemplate in sm device.
 */
export const SM_COL_TEMPLATE: string = '1fr';

/**
 * The value of  attribute of columnsTemplate in md device.
 */
export const MD_COL_TEMPLATE: string = '1fr';

/**
 * The value of  attribute of columnsTemplate in lg device.
 */
export const LG_COL_TEMPLATE: string = '1fr 1fr';

/**
 * The value of  attribute of columnsTemplate in xl device.
 */
export const XL_COL_TEMPLATE: string = '1fr 1fr';

/**
 * Initialization of attribute columnsTemplate.
 */
export const INITIALIZE_TEMPLATE: string = '1fr 1fr';

/**
 * Breakpoint name.
 */
